Todo: sloučit povídky povídkových filmů do 1 řádku?

In [1]:
import re
import os

In [2]:
import pandas as pd

In [3]:
df = pd.read_json(os.path.join("data", "filmy_raw.json"))

In [4]:
df

Film   
0                             Tábor padlých žen (10144)  \
1                         Eastern – Krvavý Hugo (10173)   
2                                 O Ječmínkovi (102282)   
3                                   Zimní víla (102314)   
4                                    Narkoblues (10242)   
...                                                 ...   
4531  Hotel Sarajevo aneb Sny obyčejného svatebčana ...   
4532                              Zdivočelá země (9738)   
4533                                     Biograf (9769)   
4534                                  Knoflíkáři (9793)   
4535                     Baader Meinhof Komplex (99894)   

                                            Země původu  Copyright Rok výroby   
0     Slovensko,                                    ...       1997       1997  \
1                                       Česká republika       1997       1997   
2                                       Česká republika       2003       2002   
3                                       Česká republika       1999       1999   
4     Česká republika,                              ...       1997       1997   
...                                                 ...        ...        ...   
4531                                    Česká republika       1997       1997   
4532                                    Česká republika       1997       1997   
4533                                    Česká republika       1997       1997   
4534                                    Česká republika       1997       1997   
4535  Spolková republika Německo,                   ...       2008       2008   

                                               Premiéra  Minutáž   
0     premiéra 28. 9. 2000 /doporučená přístupnost o...  100 min  \
1     nedistribuční premiéra 27. 4. 1997            ...    6 min   
2     nedistribuční premiéra 18. 4. 2003  (televizní...   61 min   
3     nedistribuční premiéra 24. 12. 1999  (televizn...   52 min   
4         premiéra 10. 11. 2016 /přístupné bez omezení/    9 min   
...                                                 ...      ...   
4531                               premiéra 12. 8. 1997     None   
4532  premiéra 13. 11. 1997 /přístupný/ (kino 64 U H...  114 min   
4533  nedistribuční premiéra 12. 6. 1997            ...    5 min   
4534  premiéra 20. 11. 1997 /doporučená přístupnost ...  102 min   
4535  slavnostní premiéra 8. 4. 2009  (kino Světozor...  150 min   

                                        Režie Kategorie   
0                                 Laco Halama      film  \
1                          Aurel Klimt (1189)      film   
2                        Milan Cieslar (3593)      film   
3                      Kryštof Hanzlík (1055)      film   
4     Břetislav Pojar (3113), Ivan Vít (3030)      film   
...                                       ...       ...   
4531                   Rodrigo Morales (3466)      film   
4532                       Hynek Bočan (2947)      film   
4533                     Galina Hůlová (7957)      film   
4534                      Petr Zelenka (4806)      film   
4535                         Uli Edel (50906)      film   

                                              Žánr   
0                         historický, tragikomedie  \
1                                         groteska   
2                                          pohádka   
3                                          pohádka   
4                                         osvětový   
...                                            ...   
4531                                       povídka   
4532                       dobrodružný, historický   
4533                                      anekdota   
4534                            komedie, povídkový   
4535  historický, politický, thriller, životopisný   

                               Typologie  ... Podnázev anglický   
0                     hraný, distribuční  ...              None  \
1     animovaný, distribuční, studentský  ...              N

In [5]:
", ".join(df.columns.to_list())

'Film, Země původu, Copyright, Rok výroby, Premiéra, Minutáž, Režie, Kategorie, Žánr, Typologie, Originální název, Český název, Anglický název, Souběžný název, Pracovní název, Hrají, Postavy, Pomocná režie, Asistent režie, Původní filmový námět, Scénář, Dramaturg, Kamera, Asistent kamery, Architekt, Návrhy kostýmů, Masky, Střih, Zvuk, Producent, Vedoucí výroby, Zástupce vedoucího výroby, Odborný poradce, Hudba, Choreografie, Lokace, Distribuční slogan, Výrobce, S podporou, Nositelé copyrightu, Distribuce, Délka, Distribuční nosič, Poměr stran, Barva, Zvukový systém/formát, Verze, Mluveno, Podtitulky, Úvodní/závěrečné titulky, Anotace, Obsah, Technický scénář, Výtvarník, Animace, Triky, Postprodukce, Návrhy titulků, Pedagogické vedení, Použitá hudba, Studentský film, Původní metráž, Mezititulky, Ocenění, Poznámka, Mluví, Vizuální efekty, Vedoucí produkce, Předloha, Kaskadéři, Text písně, Zpívá, pásmo, Části, Produkce, Výtvarná spolupráce, Nahrál, Partner, Animační technika, Výprava, Spo

## Převedení položek oddělených čárkami na seznamy pro snadné .explode() v budoucnu

In [6]:
seznamove_sloupce = [
    "Animace",
    "Animační technika",
    "Architekt",
    "Asistent kamery",
    "Asistent režie",
    "Ateliéry",
    "Autor komentáře",
    "Barva",
    "Distribuční nosič",
    "Dramaturg",
    "Druhá kamera",
    "Hudba",
    "Choreografie",
    "Kamera",
    "Kaskadéři",
    "Koordinátor kaskadérů",
    "Koproducent",
    "Masky",
    "Mezititulky",
    "Mluveno",
    "Natáčecí formát",
    "Návrhy kostýmů",
    "Návrhy titulků",
    "Odborný poradce",
    "Pedagogické vedení",
    "Podtitulky",
    "Pomocná režie",
    "Postprodukce",
    "Producent",
    "Produkce",
    "Předloha",
    "Původní filmový námět",
    "Režie",
    "Scénář",
    "Spolupráce",
    "Střih",
    "Technický scénář",
    "Typologie",
    "Úvodní/závěrečné titulky",
    "Vedoucí produkce",
    "Vedoucí výroby",
    "Verze",
    "Výprava",
    "Výkonná produkce",
    "Výtvarná spolupráce",
    "Výtvarník",
    "Zástupce vedoucího produkce",
    "Zástupce vedoucího výroby",
    "Země původu",
    "Zpívá",
    "Zvuk",
    "Zvukový systém/formát",
    "Žánr"]

In [7]:
seznamove_sloupce_firmy = [
    "Distribuce",
    "Nositelé copyrightu",
    "Partner",
    "S podporou",
    "Triky",
    "Vizuální efekty",
    "Výrobce",
    "Zvláštní efekty"
]

In [8]:
jiz_seznam = [
    "Dirigent",
    "Hudba k písni",
    "Nahrál",
    "Písně",
    "Použitá hudba",
    "Tančí",
    "Text písně",
    "Hudební dramaturgie",
    "Hudební režie",
    "Výběr hudby",
    "Zpěv role"
]

## Funkce pro čištění

In [9]:
def citlivy_orez(x):
    if isinstance(x, str):
        x = x.strip()
    if isinstance(x, list):
        try:
            x = [y.strip() for y in x]
        except:
            pass
    return(x)

In [10]:
def do_seznamu(polozka):
    try:
        if "," in polozka:
            polozka = str(polozka).split(",")
            polozka = [p.strip() for p in polozka]
    except:
        pass
    return(polozka)

In [11]:
def firmy_do_seznamu(polozka):
    if polozka:
        polozka = re.sub("\s"," ",polozka)
        polozka = re.sub("\n"," ",polozka)
        polozka = polozka.replace(" spol. s "," s. ").replace(" spol.s "," s. ").replace("s.r.o.","s. r. o.").replace("s. r.o.","s. r. o.").replace("a.s.","a. s.").replace(", s. r. o."," s. r. o.").replace(",s. r. o."," s. r. o.").replace(", a. s."," a. s.").replace(",a. s."," a. s.").replace(", v. o. s."," v. o. s.").replace("ČESKÁ TELEVIZE","Česká televize").replace("BONTONFILM","Bontonfilm").replace("FALCON","Falcon")
        polozka = do_seznamu(polozka)
    else:
        polozka = polozka
    return(polozka)

## Čištěníčko

In [12]:
df = df.apply(lambda x: citlivy_orez(x))

In [13]:
for s in seznamove_sloupce:
    df[s] = df[s].apply(lambda x: do_seznamu(x))
for s in seznamove_sloupce_firmy:
    df[s] = df[s].apply(lambda x: firmy_do_seznamu(x))

In [14]:
def seznam_lokaci(lokace_hrube):
    lokace_ciste = []
    if lokace_hrube:
        lokace_hrube = lokace_hrube.split("),")
        for x in lokace_hrube:
            if "(" in x:
                x = x + ")"
            x = x.strip()
            x = x.replace("))",")")
            if x[0:2] == ", ":
                x = x[2:]
            if x != ")":
                lokace_ciste.append(x)
    return(lokace_ciste)

In [15]:
df["Lokace"] = df["Lokace"].apply(lambda x: seznam_lokaci(x))

In [16]:
df["Minutáž"] = df["Minutáž"].apply(lambda x: str(x).replace("min","").strip())
df["Minutáž"] = pd.to_numeric(df["Minutáž"], errors="coerce")

In [17]:
def ratio(x):
    if x:
        x = x.replace("1:","")
        x = x.split(", ")
        x = [y.strip() for y in x]
        x = [y.replace(",",".") for y in x]
        x = [pd.to_numeric(y) for y in x]
        if len(x) == 1:
            x = x[0]
    return(x)

In [18]:
df["Poměr stran"] = df["Poměr stran"].apply(lambda x: ratio(x))

In [19]:
def metraz(x):
    if x:
        x = int(x.replace("metrů","").replace(" ",""))
    else:
        x = x
    return x

In [20]:
df["Původní metráž"] = df["Původní metráž"].apply(lambda x: metraz(x))

In [21]:
def kill_whitespace(x):
    def seriously(y):
        y = re.sub("\s+", " ", y)
        return(y)
    if isinstance(x, list):
        x = [seriously(y) for y in x]
    if isinstance(x, str):
        x = seriously(x)
    return(x)

In [22]:
df["Ocenění"] = df["Ocenění"].apply(lambda x: kill_whitespace(x))

In [23]:
def roky_vyroby(x):
    if x:
        zacatek = int(x[:4])
        konec = int(x[-4:])
    else:
        zacatek = None
        konec = None
    return [zacatek, konec]

In [24]:
df["Začátek výroby"] = df["Rok výroby"].apply(lambda x: roky_vyroby(x)[0])
df["Konec výroby"] = df["Rok výroby"].apply(lambda x: roky_vyroby(x)[1])

In [25]:
df = df.sort_values(by = "Copyright")

## Oprava minutáže

In [26]:
df[df["Minutáž"] > 130].groupby(["Film","Copyright"])["Minutáž"].max().nlargest(60)

Film                                                                                                                                              Copyright
Místo v houfu (396595)                                                                                                                            1964         1112.0
Hrdina divokého západu (402185)                                                                                                                   1920          700.0
Zapomenuté transporty (79193)                                                                                                                     2007          341.0
Komunismus a síť, aneb Konec zastupitelské demokracie (402026)                                                                                    2019          337.0
Bohemia docta aneb Labyrint světa a lusthauz srdce /Božská komedie/ (17002)                                                                       2000          254.0
Kdo bude hlída

- Místo v houfu (396595) – Zjevná chyba, nahradíme údajem z ČSDF.
- Venoušek a Stázička, Vojta Lavička: Nahoru a dolů (103360) – dtto
- Hrdina divokého západu (402185) – Složitější: "Humorné příhody Eddieho Pola a Marie Walcampové v „15 epizodách a 142 dílech“. Nejméně špatné ze špatných řešení: nahradíme mediánem za rok 1920, takže to nerozdrbe statistiky.
- Zapomenuté transporty (79193) – vyhazujeme, nechávám jednotlivé díly.

In [28]:
df.loc[df["Film"] == "Místo v houfu (396595)","Minutáž"]=115
df.loc[df["Film"] == "Venoušek a Stázička (395308)","Minutáž"]=68
df.loc[df["Film"] == "Vojta Lavička: Nahoru a dolů (103360)","Minutáž"]=89
df.loc[df["Film"] == "Hrdina divokého západu (402185)","Minutáž"]=df[df["Copyright"] == 1920]["Minutáž"].median().astype(int)
df = df[~(df["Film"] == "Zapomenuté transporty (79193)")]

In [29]:
df = df.drop(labels="cyklus", axis=1)

## Odstranění exilových filmů M. Formana a bondovky

In [31]:
exil = ['Taking Off (401352)',
        'Viděno osmi (401497)',
        'Přelet nad kukaččím hnízdem (401353)',
        'Vlasy (401378)',
        'Ragtime (401385)',
        'Amadeus (401253)',
        'Valmont (401384)',
        'Lid versus Larry Flynt (401455)',
        'Muž na Měsíci (401456)',
        'Rabín, kněz a krásná blondýna (401629)',
        'Goyovy přízraky (54226),'
        'Casino Royale (47114)']

In [32]:
df = df[~df.Film.isin(exil)]

## Kontrola, export

In [33]:
with open(os.path.join("seznamove_sloupce.txt"), "w+", encoding = "utf-8") as s_sloupce:
    s_sloupce.writelines("\n".join(seznamove_sloupce))
    s_sloupce.writelines("\n")
    s_sloupce.writelines("\n".join(seznamove_sloupce_firmy))
    s_sloupce.writelines("\n")
    s_sloupce.writelines("\n".join(jiz_seznam))

In [34]:
with open(os.path.join("dlouhometrazni.txt"), "w+", encoding = "utf-8") as dlouhometrazni:
    dlouhometrazni.writelines("\n".join(df[df["Délka"] == "dlouhometrážní"]["Film"].drop_duplicates().to_list()))

In [35]:
", ".join(df.columns.to_list())

'Film, Země původu, Copyright, Rok výroby, Premiéra, Minutáž, Režie, Kategorie, Žánr, Typologie, Originální název, Český název, Anglický název, Souběžný název, Pracovní název, Hrají, Postavy, Pomocná režie, Asistent režie, Původní filmový námět, Scénář, Dramaturg, Kamera, Asistent kamery, Architekt, Návrhy kostýmů, Masky, Střih, Zvuk, Producent, Vedoucí výroby, Zástupce vedoucího výroby, Odborný poradce, Hudba, Choreografie, Lokace, Distribuční slogan, Výrobce, S podporou, Nositelé copyrightu, Distribuce, Délka, Distribuční nosič, Poměr stran, Barva, Zvukový systém/formát, Verze, Mluveno, Podtitulky, Úvodní/závěrečné titulky, Anotace, Obsah, Technický scénář, Výtvarník, Animace, Triky, Postprodukce, Návrhy titulků, Pedagogické vedení, Použitá hudba, Studentský film, Původní metráž, Mezititulky, Ocenění, Poznámka, Mluví, Vizuální efekty, Vedoucí produkce, Předloha, Kaskadéři, Text písně, Zpívá, pásmo, Části, Produkce, Výtvarná spolupráce, Nahrál, Partner, Animační technika, Výprava, Spo

In [36]:
df

Film   
3761   Polední výstřel na Mariánských hradbách (401709)  \
3756    Cvičení s kužely Sokolů malostranských (401704)   
3757                                  Cyklisté (401705)   
3758  Defilování vojska o Božím těle na Královských ...   
3759                         Hanácké banderium (401707)   
...                                                 ...   
4209                         Mimořádná událost (402176)   
4206                       Po čem muži touží 2 (402173)   
4220                              Až zařve lev (402204)   
4230                             Planeta Praha (402218)   
4199                               Identita ES (402166)   

                               Země původu  Copyright            Rok výroby   
3761                      Rakousko-Uhersko       1898                  1898  \
3756                      Rakousko-Uhersko       1898                  1898   
3757                      Rakousko-Uhersko       1898                  1898   
3758                      Rakousko-Uhersko       1898                  1898   
3759                      Rakousko-Uhersko       1898                  1898   
...                                    ...        ...                   ...   
4209                       Česká republika       2022                  2021   
4206          [Česká republika, Slovensko]       2022                  2021   
4220                       Česká republika       2022             2020—2021   
4230          [Česká republika, Slovensko]       2022             2020—2021   
4199  [Česká republika, Kanada, Slovensko]       2022  2015—2016, 2020—2021   

                                               Premiéra  Minutáž   
3761  premiéra 19. 6. 1898  (Výstava architektury a ...      1.0  \
3756  premiéra 24. 7. 1898  (Výstava architektury a ...      1.0   
3757  premiéra léto 1898  (Výstava architektury a in...      1.0   
3758  premiéra 19. 6. 1898  (Výstava architektury a ...      1.0   
3759  premiéra 24. 7. 1898  (Výstava architektury a ...      1.0   
...                                                 ...      ...   
4209  slavnostní premiéra 2. 2. 2022  (kino Lucerna,...    102.0   
4206  slavnostní premiéra 20. 4. 2022  (multiplex Ci...     96.0   
4220  slavnostní premiéra 5. 4. 2022  (kino Lucerna,...    104.0   
4230  slavnostní premiéra 2. 8. 2022  (kino Aero, Pr...     89.0   
4199  slavnostní premiéra 2. 3. 2022  (kino Oko, Pra...     79.0   

                        Režie Kategorie                                 Žánr   
3761  Jan Kříženecký (127419)      film                             reportáž  \
3756  Jan Kříženecký (127419)      film                [reportáž, sportovní]   
3757  Jan Kříženecký (127419)      film                             reportáž   
3758  Jan Kříženecký (127419)      film                             reportáž   
3759  Jan Kříženecký (127419)      film                             reportáž   
...                       ...       ...                                  ...   
4209     Jiří Havelka (28977)      film  [komedie, satira, bláznivá komedie]   
4206    Rudolf Havlík (79764)      film               [fantastický, komedie]   
4220    Jan E. Svatoš (77843)      film      [historický, životopisný, esej]   
4230         Jan Hošek (5629)      film              [přírodopisný, rodinný]   
4199   Alena Činčerová (5732)      film                             medailon   

                        Typologie  ... Výtvarník pozadí Výrobní skupina   
3761  [dokumentární, distribuční]  ...             None            None  \
3756  [dokumentární, distribuční]  ...             None            None   
3757  [dokumentární, distribuční]  ...             None            None   
3758  [dokumentární, distribuční]  ...             None            None   
3759  [dokumentární, distribuční]  ...             None            None   
...                           ...  ...              ...             ...   
4209         [hraný, distribuční]  ...             None            None   
4206         [h

In [37]:
df.to_json(os.path.join("data", "filmy.json"), orient="records")

In [38]:
import zipfile
try:
    import zlib
    mode= zipfile.ZIP_DEFLATED
except:
    mode= zipfile.ZIP_STORED

In [39]:
with zipfile.ZipFile(os.path.join("data", "filmy.zip"), mode="w") as my_zip:
    my_zip.write(os.path.join("data", "filmy.json"), compress_type=zipfile.ZIP_DEFLATED)